### ISSUE TITLE
Request: Parabox increment style config options

### ISSUE THREAD

**Issue by LezChap** [Shadows-of-Fire/Parabox#11]
Right now, the parabox increments linearly. Every loop, you need 10k more RF (or whatever it's configured to). I think there should be a few more options...some ideas would be for each loop where it doubles the previous loop requirement, or another where it will square the previous loop requirement. Like my previous request, this should make running longer loops a lot more difficult to accomplish.

Reposting here as I posted in the wrong Github originally: https://github.com/Darkhax-Minecraft/Parabox/issues/3

**Comment by Shadows-of-Fire** [comment]
Parabox is not taking feature requests at this time.

**Comment by awesome816gamer** [comment]
the loop option is greyed out and I dont know how to loop it
