### ISSUE TITLE
Server Does not Reboot

### ISSUE THREAD

**Issue by RobertLSnead** [Shadows-of-Fire/Parabox#14]
Server shutsdown but does not reboot.
Manual restart/start has to be done! - Not great for admins!!!!

Parabox-1.12.2-1.1.4

**Comment by Shadows-of-Fire** [comment]
It can't

**Comment by RobertLSnead** [comment]
That is just annoying, I have the mod now removed.

I don't need players stopping the server and complain to have it rebooted, if there is no way to accomplish this.


Thanks for your help!

**Comment by justinrusso** [comment]
http://lmgtfy.com/?q=automatically+restart+minecraft+server

**Comment by RobertLSnead** [comment]
That method does not work on Nitrous server control panel!
Will need to contact customer support in order to allow auto restart.
I'm not too familiar with tasks and startup commands in that fashion, let alone the parameters set on the server for memory etc.

**Comment by RobertLSnead** [comment]
Placed a ticket!
It will have to be something they will have to do on their end as this is not possible on my side!
If all is well, I can reload the mod and enjoy as intended!

**Comment by RobertLSnead** [comment]
Just wanted to let you know I was able to get it to work! :D
Thanks for the help!

**Comment by johnfriedrich** [comment]
You could atleast add a config option to define another command than stop. We have a /restart comand which could be used but the mod doesn't let me
