### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by RobertLSnead** [Shadows-of-Fire/Parabox#15]
When placing the parabox the client crashes.
This happens in compact machines and in the main over world for Sky Factory 4.
Does not affect server or other players.

Parabox-1.12.2-1.1.4

**Comment by RobertLSnead** [comment]
Crash Report:
https://pastebin.com/rY4gZP2u

**Comment by Shadows-of-Fire** [comment]
This is resolved as of the 2.x.x update but will not be released until that point.
