### ISSUE TITLE
Parabox no longer able to be sped up with watches of flowing time from project e

### ISSUE THREAD

**Issue by JackRuby1** [Shadows-of-Fire/Parabox#19]
Now that the parabox requires items for faster times, watches of flowing time from project e no longer speed it up. It looks like it's trying to do it, but failing. https://gyazo.com/f4a9e7f45ea9bd9da80ef4efce65d19c

**Comment by Shadows-of-Fire** [comment]
If your rf/t is at 0, it shouldn't even tick down naturally at all.  I'm surprised that's doing anything.

**Comment by JackRuby1** [comment]
Oh then that's another bug, I have a flux point connected to it with limitless transfer.

**Comment by Shadows-of-Fire** [comment]
Depending on what parabox jar you're using the sync may still be broken.  It should be fixed on the beta that's on CF.

**Comment by JackRuby1** [comment]
Yup, already on that one.  The 0 rf/t is happening because of the watches, if I turn the parabox on without them it's fine, but if I turn the watches on it goes to 0 rf/t

**Comment by Shadows-of-Fire** [comment]
Well at that point it's going to be what te the watch decides to speed up first.  The only way a watch works with the RF/t model is if the parabox receives another power tick before it ticks itself, which is probably not happening.

**Comment by JackRuby1** [comment]
I updated my comment, it's the watches breaking the rf/t

**Comment by JackRuby1** [comment]
https://gyazo.com/777368736df2c9ff9014a5a5e0a4c525 you can see once I turn the watch on, it goes to 0 rf/t

**Comment by Shadows-of-Fire** [comment]
Unfortunately due to how the rf/t model works alongside the watch I don't think they can work together anymore.
