### ISSUE TITLE
Malformed / Corrupted parabox.json in single player words

### ISSUE THREAD

**Issue by Sanduhr32** [Shadows-of-Fire/Parabox#9]
# Issue Type
- [x] Bug

## Description
Recently I got contacted by a polite member of a discord server I'm part of. He asked me to evaluate his [crashlog](http://bit.ly/crashreportSkyFac4) and I immediately noticed that a saved json file has to be at least malformed (heavily corrupted or encrypted) when it is read and parsed into a JSON object by Google's GSON library.

Of course I could exclude that the library showed an unexpected behavior so I asked for the world folder and opened the parabox.json of his SkyFactory 4 world and bursted out in laughter after seeing how malformed the json was.

### Idea for providing a fix
Providing the default config in case of a missing, malformed config file.

**Comment by Shadows-of-Fire** [comment]
Well, that's unusual.  I'll put a try/catch around that read for that kind of exception then.
